apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2023-06-30T20:14:55Z"
  generation: 11
  name: guestbook
  namespace: argocd
  resourceVersion: "1723"
  uid: b4e8de31-2995-4a8e-bb53-b764df159ab0
spec:
  destination:
    namespace: guestbook
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: master
